[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.19"    # Solana version to use(applies to all Solana tools)

[features]
seeds = false
skip-lint = false

[programs.mainnet]
atomic_art_upgrades = "JCp7WqJMX5qQucBkChrem5JZFjJxN12dmxvJGqNp724C"

[programs.devnet]
atomic_art_upgrades = "JCp7WqJMX5qQucBkChrem5JZFjJxN12dmxvJGqNp724C"

[programs.localnet]
atomic_art_upgrades = "JCp7WqJMX5qQucBkChrem5JZFjJxN12dmxvJGqNp724C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/programs/packages/tests/fixtures/id.json"

[scripts]
createConfig = "yarn run ts-node packages/scripts/createUpgradeConfig.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 packages/tests/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "packages/tests/fixtures/mpl_token_metadata.so"
