[workspace]
types = "packages/types"

[features]
seeds = false
skip-lint = false
[programs.devnet]
atomic_art_upgrades = "8EidSNJMiPUWcB8pXLnBG2k6nL4nqWwutPL5To5yY8Hh"
[programs.localnet]
atomic_art_upgrades = "8EidSNJMiPUWcB8pXLnBG2k6nL4nqWwutPL5To5yY8Hh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/elo/Code/solana/rogue-sharks/programs/packages/tests/fixtures/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 packages/tests/*.ts"
createConfig = "yarn run ts-node packages/scripts/createUpgradeConfig.ts"


[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "packages/tests/fixtures/mpl_token_metadata.so"
