[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.19"

[features]
seeds = false
skip-lint = false

[programs.devnet]
atomic_art_upgrades = "3RuRdvZPVqqTqa7MDqgsDPVUnm8QYdYQc4zZkAXS9HMn"

[programs.localnet]
atomic_art_upgrades = "3RuRdvZPVqqTqa7MDqgsDPVUnm8QYdYQc4zZkAXS9HMn"

[programs.mainnet]
atomic_art_upgrades = "3RuRdvZPVqqTqa7MDqgsDPVUnm8QYdYQc4zZkAXS9HMn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/rhovian.json"

[scripts]
createConfig = "yarn run ts-node packages/scripts/createUpgradeConfig.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 packages/tests/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "packages/tests/fixtures/mpl_token_metadata.so"
